CreateConVar("tdm_spawn", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Allow sandbox spawning.", 0, 1)
CreateConVar("tdm_deathcam", 5, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Deathcam.")
CreateConVar("tdm_regen_enabled", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Health regen", 0, 1)
CreateConVar("tdm_regen_speed", 100 / 8, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How much to regenerate in a second")
CreateConVar("tdm_regen_delay", 5, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How long it takes to start regenerating")
CreateConVar("tdm_stamina_drain", 4, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How long it takes to drain stamina")
CreateConVar("tdm_stamina_gain", 3, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How long it takes to regain stamina")
CreateConVar("tdm_stamina_wain", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How long it takes to start recharging")
CreateConVar("tdm_jump_gain", 0.5, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How long it takes to get full jump")
CreateConVar("tdm_jump_power", 220, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Jump power")

CreateConVar("tdm_ff", 0.25, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Friendly fire damage percent (0 is no damage).", 0, 1)
CreateConVar("tdm_ff_reflect", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Excessive friendly fire damage will reflect.", 0, 1)
CreateConVar("tdm_ff_reflect_threshold", 300, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Amount of (pre-reduced) friendly damage to trigger reflect.", 0)
CreateConVar("tdm_ff_reflect_cap", 600, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Maximum amount of friendly damage to track.", 0)
CreateConVar("tdm_ff_reflect_decay", 150, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Friendly fire threshold decays by this much every minute. When it reaches zero, damage will no longer reflect", 0)